### PR TITLE
Copy JavaPoet

### PR DESCRIPTION
**Pull request by dstepanov**
To support records etc
https://github.com/square/javapoet/pull/981

### CODE REVIEW

**Review by graemerocher — APPROVED** [review]

**Review by melix — COMMENTED** [review]
I'm a little uncomfortable at the idea of copying the entire JavaPoet library here, it's going to make maintenance harder. Also if we do so _and_ that we build a wrapper on top of it and KotlinPoet, maybe it's redundant altogether...

**Comment by dstepanov** [comment]
What do you mean by redundant? JavaPoet is not maintained anymore but KotlinPort I think it is

**Comment by melix** [comment]
I mean that if we build something on top of both JavaPoet and KotlinPoet, and that we have to copy the JavaPoet implementation in any case, we might be better building a model that can generate both Java and Kotlin code directly, inspired from these.

**Comment by dstepanov** [comment]
Java and Kotlin poet have different APIs, the other option would be use the Java poet API and convert it to Kotlin, I don’t think that’s a good idea, we don’t really want to use very opinionated Java Poet API

**Comment by dstepanov** [comment]
I did include records support from https://github.com/FabricMC/javapoet repo

**Pull request merged**
